//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialUI.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class К_Карта
    {
        public int Id { get; set; }
        public int Клиент { get; set; }
        public byte Абонемент { get; set; }
        public System.DateTime ДатаНачала { get; set; }
        public System.DateTime ДатаОкончания { get; set; }
        public byte Статус { get; set; }
    
        public virtual Абонемент Абонемент1 { get; set; }
        public virtual Клиент Клиент1 { get; set; }
        public virtual Статус Статус1 { get; set; }
    }
}
