//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialUI.DateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Посещения
    {
        public int Id { get; set; }
        public Nullable<byte> Услуга { get; set; }
        public Nullable<int> Клиент { get; set; }
        public System.DateTime Дата { get; set; }
        public System.TimeSpan Время { get; set; }
        public byte Помещение { get; set; }
    
        public virtual Клиент Клиент1 { get; set; }
        public virtual Помещение Помещение1 { get; set; }
        public virtual Услуга Услуга1 { get; set; }
    }
}
