//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialUI.DateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Расписание
    {
        public byte Id { get; set; }
        public byte Тренер { get; set; }
        public byte День { get; set; }
        public System.TimeSpan С { get; set; }
        public System.TimeSpan До { get; set; }
    
        public virtual ДниНедели ДниНедели { get; set; }
        public virtual Тренер Тренер1 { get; set; }
    }
}
